### ISSUE TITLE
[BUG] Frequent disconnects with latest version

### ISSUE THREAD

**Issue by bdraco** [gwww/elkm1#54]
I'm submitting the trace as a placeholder so I don't forget as I haven't had a free moment to investigate.

```
2022-04-17 18:01:48 ERROR (MainThread) [homeassistant] Error doing job: application protocol failed to receive SSL data
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 545, in data_received
    self._app_protocol.data_received(chunk)
  File "/usr/local/lib/python3.9/site-packages/elkm1_lib/connection.py", line 242, in data_received
    self._got_data_callback(line)
  File "/usr/local/lib/python3.9/site-packages/elkm1_lib/connection.py", line 137, in _got_data_callback
    self._msg_decode.decode(data)
  File "/usr/local/lib/python3.9/site-packages/elkm1_lib/message.py", line 75, in decode
    self.call_handlers(cmd, decoder(msg))
  File "/usr/local/lib/python3.9/site-packages/elkm1_lib/message.py", line 63, in call_handlers
    handler(**decoded_msg)
TypeError: _ee_handler() got an unexpected keyword argument 'area'
2022-04-17 18:01:48 WARNING (MainThread) [elkm1_lib.connection] ElkM1 at elks://192.168.209.56 disconnected
```

**Comment by gwww** [comment]
I’ll take a look. Is this from the latest change ?

**Comment by bdraco** [comment]
> Is this from the latest change ?

95% sure it is

**Comment by gwww** [comment]
Testing fix now.

**Comment by gwww** [comment]
HA PR created.
