### ISSUE TITLE
[BUG] RuntimeError: list changed size during iteration

### ISSUE THREAD

**Issue by jimboca** [gwww/elkm1#63]
**Describe the bug**

First time I have seen this happen.  This instance was still running a local version of elkm1_lib with my latest changes before you merged them.

```
2022-08-22 06:30:03,798 ELK-49551  udi_interface      ERROR    udi_interface:write: Exception in thread
2022-08-22 06:30:03,800 ELK-49551  udi_interface      ERROR    udi_interface:write: ELK-49551
2022-08-22 06:30:03,801 ELK-49551  udi_interface      ERROR    udi_interface:write: :
2022-08-22 06:30:03,801 ELK-49551  udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2022-08-22 06:30:03,802 ELK-49551  udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
2022-08-22 06:30:03,807 ELK-49551  udi_interface      ERROR    udi_interface:write: self.run()
2022-08-22 06:30:03,808 ELK-49551  udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.9/threading.py", line 917, in run
2022-08-22 06:30:03,812 ELK-49551  udi_interface      ERROR    udi_interface:write: self._target(*self._args, **self._kwargs)
2022-08-22 06:30:03,813 ELK-49551  udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/00:0d:b9:52:bf:fc_4/nodes/Controller.py", line 482, in _elk_start
2022-08-22 06:30:03,817 ELK-49551  udi_interface      ERROR    udi_interface:write: self.elk.run()
2022-08-22 06:30:03,818 ELK-49551  udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/00:0d:b9:52:bf:fc_4/elkm1_lib/elk.py", line 119, in run
2022-08-22 06:30:03,820 ELK-49551  udi_interface      ERROR    udi_interface:write: self.loop.run_forever()
2022-08-22 06:30:03,822 ELK-49551  udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
2022-08-22 06:30:03,825 ELK-49551  udi_interface      ERROR    udi_interface:write: self._run_once()
2022-08-22 06:30:03,826 ELK-49551  udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1858, in _run_once
2022-08-22 06:30:03,833 ELK-49551  udi_interface      ERROR    udi_interface:write: handle = heapq.heappop(self._scheduled)
2022-08-22 06:30:03,835 ELK-49551  udi_interface      ERROR    udi_interface:write: RuntimeError
2022-08-22 06:30:03,835 ELK-49551  udi_interface      ERROR    udi_interface:write: :
2022-08-22 06:30:03,836 ELK-49551  udi_interface      ERROR    udi_interface:write: list changed size during iteration
```

**To Reproduce**

This happened when I armed the system which I have done many times and have not seen this happen.

**Expected behavior**

No crash.

**Screenshots**

**Versions (please complete the following information):**
 - ElkM1 version: 2.1.0 (pre-release)
 - Home Assistant version: N/A

**Additional context**

**Comment by gwww** [comment]
Does this happen repeatedly? I see lots of threading calls. Is that related to the way you use this library?

**Comment by jimboca** [comment]
This is the first time I've seen it, and I didn't trap this so my program crashed.  I just start a thread which starts a asyncio.new_event_loop whhich is passed to elkm1_lib Elk method and eventually calls .run.

I will add a trap for this and see if it happens again.

**Comment by gwww** [comment]
The last line of the trace is the most interesting. A list was modified while being iterated over. I have seen that before in the library but they were all cleaned up.

**Comment by jimboca** [comment]
Yes, I was looking at the asyncio code to see if it had changed much since python 3.9.13 that we are on, and I don't see much difference in that routine.

**Comment by bdraco** [comment]
It looks like there is a non thread-safe operation (ie something is being called from the wrong thread)

Try turning on debug mode:
https://docs.python.org/3/library/asyncio-dev.html#debug-mode

Since there is no threading in this library, its likely unrelated to this library.

**Comment by gwww** [comment]
Stale and not reproducible.
